export const PermissionEnum = {
  MANAGE_STAFF: "MANAGE_STAFF",
  MANAGE_CUSTOMERS: "MANAGE_CUSTOMERS",
  MANAGE_GROUPS: "MANAGE_GROUPS",
  MANAGE_PRODUCTS: "MANAGE_PRODUCTS",
  MANAGE_ATTRIBUTES: "MANAGE_ATTRIBUTES",
  MANAGE_PRODUCT_TYPES: "MANAGE_PRODUCT_TYPES",
  MANAGE_SUPPLIERS: "MANAGE_SUPPLIERS",
  MANAGE_COLLECTIONS: "MANAGE_COLLECTIONS",
  MANAGE_CATEGORIES: "MANAGE_CATEGORIES",
};
