import React from "react";

import { Controller } from "react-hook-form";
import slugify from "slugify";

import { TextField } from "@material-ui/core";

import { Card } from "@/components/Template";

export const FormUrl = (props) => {
  const { control, errors, watch } = props;
  const title = watch("title");

  return (
    <Card title="URL">
      <Controller
        as={TextField}
        control={control}
        name="slug"
        label="Slug"
        placeholder={slugify(title, { lower: true })}
        fullWidth
        error={!!errors.slug}
        helperText={
          !!errors.slug
            ? errors.slug?.message
            : "If empty, URL will be autogenerated from Page Name"
        }
      />
    </Card>
  );
};
